# Generated by Django 3.2 on 2021-05-11 06:16

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(map_id='map'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [0, 0], 'marker_color': 'blue'}),
        ),
        migrations.AlterField(
            model_name='resources',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
