# Generated by Django 3.2 on 2021-05-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210511_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
