# Generated by Django 3.2 on 2021-05-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resources_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='identifier',
        ),
    ]
