# Generated by Django 3.2 on 2021-05-17 08:30

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resources_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='review',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [22.1991660760527, 78.476681027237], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'language': 'auto', 'marker_color': 'blue', 'message_404': 'undefined address', 'navigation_buttons': True, 'placeholder': 'Pick a location on map below', 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/streets-v11', 'track_location_button': True, 'zoom': 30}),
        ),
    ]
