# Generated by Django 2.0.5 on 2022-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20220418_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_id',
        ),
        migrations.AddField(
            model_name='status',
            name='resources_id',
            field=models.IntegerField(default=0),
        ),
    ]
