# Generated by Django 2.0.5 on 2022-04-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20220418_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='resources_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='resources.resources'),
        ),
    ]
