# Generated by Django 2.0.5 on 2022-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20220418_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
