# Generated by Django 2.0.5 on 2022-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20220616_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
