# Generated by Django 2.0.5 on 2022-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20220617_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/avatar.jpg', upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Break', 'Break'), ('Open', 'open'), ('closed', 'closed')], default='Available', max_length=255),
        ),
    ]
